env:
  global:
    - CONAN_TOTAL_PAGES=8
    - CONAN_DOCKER_32_IMAGES=True
    - CONAN_REFERENCE: "qt/5.12.3"
    - CONAN_USERNAME: "appimage-conan-community"
    - CONAN_LOGIN_USERNAME: "azubieta"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/appimage-conan-community/public-conan"

linux: &linux
  os: linux
  dist: xenial
  language: python
  python: "3.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=1
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=2
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=3
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=4
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=5
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=6
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_CURRENT_PAGE=8
install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
