jobs:
- job: LinuxARM
  pool:
    vmImage: "Ubuntu 16.04"
  timeoutInMinutes: 180
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
  - script: |
      pip install --upgrade pip
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
      CONAN_ARCHS: "armv7hf"
  strategy:
    matrix:
      Gcc 5 armv7hf:
        CONAN_GCC_VERSIONS: 5
        CONAN_DOCKER_IMAGE: ericlemanissier/gcc5-armv7hf
      Gcc 6 armv7hf:
        CONAN_GCC_VERSIONS: 6
        CONAN_DOCKER_IMAGE: ericlemanissier/gcc6-armv7hf
      Gcc 7 armv7hf:
        CONAN_GCC_VERSIONS: 7
        CONAN_DOCKER_IMAGE: ericlemanissier/gcc7-armv7hf
      Gcc 8 armv7hf:
        CONAN_GCC_VERSIONS: 8
        CONAN_DOCKER_IMAGE: ericlemanissier/gcc8-armv7hf
